name: CI to Docker hub 
on:
  push:
    branches: main

jobs:

  build_push:
    runs-on: ubuntu-latest
    steps:

        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_IMAGE }}/${{ secrets.DOCKER_REPO }}:$(date +%s)

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
